;old evolution types
EV_ITEM  EQU 2
EV_TRADE EQU 3

;evolution types
EV_LEVEL EQU 1
EV_SEASON_CHANGE EQU 2
EV_LEVEL_MORALE EQU 3
EV_LEVEL_STATS EQU 4
EV_LEVEL_TILE EQU 5
EV_LEVEL_MOVES EQU 6
EV_FLUTE_MAP EQU 7
EV_LEVEL_TSET EQU 8
EV_MEGA EQU 9
EV_FLUTE_PARTY EQU 10
EV_FLUTE_TILE EQU 11
EV_FLUTE_TSET EQU 12
EV_FLUTE_HELD_ITEM EQU 13
EV_LEVEL_ABILITY EQU 14
EV_LEVEL_HELD_ITEM EQU 15

;evolution_modifiers
DAY_ONLY EQU %10000000
NIGHT_ONLY EQU %01000000
SUMMER_ONLY EQU %00100000
WINTER_ONLY EQU %00010000

EV_LAVA_TILE EQU 1
EV_GRASS_TILE EQU 2
EV_WATER_TILE EQU 3

EV_MEGA_EVOLVE EQU 1
EV_MEGA_DEVOLVE EQU 2


;egg groups byte constants:
CAN_BE_FEMALE EQU %10000000
CAN_BE_MALE   EQU %01000000

EG_NONE EQU 0
EG_CAT	EQU 1
EG_DOG EQU 2
EG_MONSTER EQU 3
EG_DRAGON EQU 3
EG_TURTLE EQU 4
EG_FROG EQU 5
EG_BUG EQU 6