SFX_Pointers_2::
	db 255,255,255
	sfx_pointer SFX_Snare1_2
	sfx_pointer SFX_Snare2_2
	sfx_pointer SFX_Snare3_2
	sfx_pointer SFX_Snare4_2
	sfx_pointer SFX_Snare5_2
	sfx_pointer SFX_Triangle1_2
	sfx_pointer SFX_Triangle2_2
	sfx_pointer SFX_Snare6_2
	sfx_pointer SFX_Snare7_2
	sfx_pointer SFX_Snare8_2
	sfx_pointer SFX_Snare9_2
	sfx_pointer SFX_Cymbal1_2
	sfx_pointer SFX_Cymbal2_2
	sfx_pointer SFX_Cymbal3_2
	sfx_pointer SFX_Muted_Snare1_2
	sfx_pointer SFX_Triangle3_2
	sfx_pointer SFX_Muted_Snare2_2
	sfx_pointer SFX_Muted_Snare3_2
	sfx_pointer SFX_Muted_Snare4_2
	sfx_pointer SFX_Cry00_2
	sfx_pointer SFX_Cry01_2
	sfx_pointer SFX_Cry02_2
	sfx_pointer SFX_Cry03_2
	sfx_pointer SFX_Cry04_2
	sfx_pointer SFX_Cry05_2
	sfx_pointer SFX_Cry06_2
	sfx_pointer SFX_Cry07_2
	sfx_pointer SFX_Cry08_2
	sfx_pointer SFX_Cry09_2
	sfx_pointer SFX_Cry0A_2
	sfx_pointer SFX_Cry0B_2
	sfx_pointer SFX_Cry0C_2
	sfx_pointer SFX_Cry0D_2
	sfx_pointer SFX_Cry0E_2
	sfx_pointer SFX_Cry0F_2
	sfx_pointer SFX_Cry10_2
	sfx_pointer SFX_Cry11_2
	sfx_pointer SFX_Cry12_2
	sfx_pointer SFX_Cry13_2
	sfx_pointer SFX_Cry14_2
	sfx_pointer SFX_Cry15_2
	sfx_pointer SFX_Cry16_2
	sfx_pointer SFX_Cry17_2
	sfx_pointer SFX_Cry18_2
	sfx_pointer SFX_Cry19_2
	sfx_pointer SFX_Cry1A_2
	sfx_pointer SFX_Cry1B_2
	sfx_pointer SFX_Cry1C_2
	sfx_pointer SFX_Cry1D_2
	sfx_pointer SFX_Cry1E_2
	sfx_pointer SFX_Cry1F_2
	sfx_pointer SFX_Cry20_2
	sfx_pointer SFX_Cry21_2
	sfx_pointer SFX_Cry22_2
	sfx_pointer SFX_Cry23_2
	sfx_pointer SFX_Cry24_2
	sfx_pointer SFX_Cry25_2
	sfx_pointer SFX_Level_Up
	sfx_pointer SFX_Get_Item2_2
	sfx_pointer SFX_Tink_2
	sfx_pointer SFX_Heal_HP_2
	sfx_pointer SFX_Heal_Ailment_2
	sfx_pointer SFX_Start_Menu_2
	sfx_pointer SFX_Press_AB_2
	sfx_pointer SFX_Ball_Toss
	sfx_pointer SFX_Ball_Poof
	sfx_pointer SFX_Faint_Thud
	sfx_pointer SFX_Run
	sfx_pointer SFX_Dex_Page_Added
	sfx_pointer SFX_Caught_Mon
	sfx_pointer SFX_Peck
	sfx_pointer SFX_Faint_Fall
	sfx_pointer SFX_Battle_09
	sfx_pointer SFX_Pound
	sfx_pointer SFX_Battle_0B
	sfx_pointer SFX_Battle_0C
	sfx_pointer SFX_Battle_0D
	sfx_pointer SFX_Battle_0E
	sfx_pointer SFX_Battle_0F
	sfx_pointer SFX_Damage
	sfx_pointer SFX_Not_Very_Effective
	sfx_pointer SFX_Battle_12
	sfx_pointer SFX_Battle_13
	sfx_pointer SFX_Battle_14
	sfx_pointer SFX_Vine_Whip
	sfx_pointer SFX_Battle_16
	sfx_pointer SFX_Battle_17
	sfx_pointer SFX_Battle_18
	sfx_pointer SFX_Battle_19
	sfx_pointer SFX_Super_Effective
	sfx_pointer SFX_Battle_1B
	sfx_pointer SFX_Battle_1C
	sfx_pointer SFX_Doubleslap
	sfx_pointer SFX_Battle_1E
	sfx_pointer SFX_Horn_Drill
	sfx_pointer SFX_Battle_20
	sfx_pointer SFX_Battle_21
	sfx_pointer SFX_Battle_22
	sfx_pointer SFX_Battle_23
	sfx_pointer SFX_Battle_24
	sfx_pointer SFX_Battle_25
	sfx_pointer SFX_Battle_26
	sfx_pointer SFX_Battle_27
	sfx_pointer SFX_Battle_28
	sfx_pointer SFX_Battle_29
	sfx_pointer SFX_Battle_2A
	sfx_pointer SFX_Battle_2B
	sfx_pointer SFX_Battle_2C
	sfx_pointer SFX_Psybeam
	sfx_pointer SFX_Battle_2E
	sfx_pointer SFX_Battle_2F
	sfx_pointer SFX_Psychic_M
	sfx_pointer SFX_Battle_31
	sfx_pointer SFX_Battle_32
	sfx_pointer SFX_Battle_33
	sfx_pointer SFX_Battle_34
	sfx_pointer SFX_Battle_35
	sfx_pointer SFX_Battle_36
	sfx_pointer SFX_Silph_Scope
	
	sfx_pointer Music_GymLeaderBattle
	sfx_pointer Music_TrainerBattle
	sfx_pointer Music_WildBattle
	sfx_pointer Music_FinalBattle
	sfx_pointer Music_DefeatedTrainer
	sfx_pointer Music_DefeatedWildMon
	sfx_pointer Music_DefeatedGymLeader
