SFX_Pointers_3::
	db 255,255,255
	sfx_pointer SFX_Snare1_3
	sfx_pointer SFX_Snare2_3
	sfx_pointer SFX_Snare3_3
	sfx_pointer SFX_Snare4_3
	sfx_pointer SFX_Snare5_3
	sfx_pointer SFX_Triangle1_3
	sfx_pointer SFX_Triangle2_3
	sfx_pointer SFX_Snare6_3
	sfx_pointer SFX_Snare7_3
	sfx_pointer SFX_Snare8_3
	sfx_pointer SFX_Snare9_3
	sfx_pointer SFX_Cymbal1_3
	sfx_pointer SFX_Cymbal2_3
	sfx_pointer SFX_Cymbal3_3
	sfx_pointer SFX_Muted_Snare1_3
	sfx_pointer SFX_Triangle3_3
	sfx_pointer SFX_Muted_Snare2_3
	sfx_pointer SFX_Muted_Snare3_3
	sfx_pointer SFX_Muted_Snare4_3
	sfx_pointer SFX_Cry00_3
	sfx_pointer SFX_Cry01_3
	sfx_pointer SFX_Cry02_3
	sfx_pointer SFX_Cry03_3
	sfx_pointer SFX_Cry04_3
	sfx_pointer SFX_Cry05_3
	sfx_pointer SFX_Cry06_3
	sfx_pointer SFX_Cry07_3
	sfx_pointer SFX_Cry08_3
	sfx_pointer SFX_Cry09_3
	sfx_pointer SFX_Cry0A_3
	sfx_pointer SFX_Cry0B_3
	sfx_pointer SFX_Cry0C_3
	sfx_pointer SFX_Cry0D_3
	sfx_pointer SFX_Cry0E_3
	sfx_pointer SFX_Cry0F_3
	sfx_pointer SFX_Cry10_3
	sfx_pointer SFX_Cry11_3
	sfx_pointer SFX_Cry12_3
	sfx_pointer SFX_Cry13_3
	sfx_pointer SFX_Cry14_3
	sfx_pointer SFX_Cry15_3
	sfx_pointer SFX_Cry16_3
	sfx_pointer SFX_Cry17_3
	sfx_pointer SFX_Cry18_3
	sfx_pointer SFX_Cry19_3
	sfx_pointer SFX_Cry1A_3
	sfx_pointer SFX_Cry1B_3
	sfx_pointer SFX_Cry1C_3
	sfx_pointer SFX_Cry1D_3
	sfx_pointer SFX_Cry1E_3
	sfx_pointer SFX_Cry1F_3
	sfx_pointer SFX_Cry20_3
	sfx_pointer SFX_Cry21_3
	sfx_pointer SFX_Cry22_3
	sfx_pointer SFX_Cry23_3
	sfx_pointer SFX_Cry24_3
	sfx_pointer SFX_Cry25_3
	sfx_pointer SFX_Get_Item1_3
	sfx_pointer SFX_Get_Item2_3
	sfx_pointer SFX_Tink_3
	sfx_pointer SFX_Heal_HP_3
	sfx_pointer SFX_Heal_Ailment_3
	sfx_pointer SFX_Start_Menu_3
	sfx_pointer SFX_Press_AB_3
	sfx_pointer SFX_Pokedex_Rating_3
	sfx_pointer SFX_Get_Key_Item_3
	sfx_pointer SFX_Poisoned_3
	sfx_pointer SFX_Trade_Machine_3
	sfx_pointer SFX_Turn_On_PC_3
	sfx_pointer SFX_Turn_Off_PC_3
	sfx_pointer SFX_Enter_PC_3
	sfx_pointer SFX_Shrink_3
	sfx_pointer SFX_Switch_3
	sfx_pointer SFX_Healing_Machine_3
	sfx_pointer SFX_Teleport_Exit1_3
	sfx_pointer SFX_Teleport_Enter1_3
	sfx_pointer SFX_Teleport_Exit2_3
	sfx_pointer SFX_Ledge_3
	sfx_pointer SFX_Teleport_Enter2_3
	sfx_pointer SFX_Fly_3
	sfx_pointer SFX_Denied_3
	sfx_pointer SFX_Arrow_Tiles_3
	sfx_pointer SFX_Push_Boulder_3
	sfx_pointer SFX_SS_Anne_Horn_3
	sfx_pointer SFX_Withdraw_Deposit_3
	sfx_pointer SFX_Cut_3
	sfx_pointer SFX_Go_Inside_3
	sfx_pointer SFX_Swap_3
	sfx_pointer SFX_59_3
	sfx_pointer SFX_Purchase_3
	sfx_pointer SFX_Collision_3
	sfx_pointer SFX_Go_Outside_3
	sfx_pointer SFX_Save_3
	sfx_pointer SFX_Intro_Lunge
	sfx_pointer SFX_Intro_Hip
	sfx_pointer SFX_Intro_Hop
	sfx_pointer SFX_Intro_Raise
	sfx_pointer SFX_Intro_Crash
	sfx_pointer SFX_Intro_Whoosh
	sfx_pointer SFX_Slots_Stop_Wheel
	sfx_pointer SFX_Slots_Reward
	sfx_pointer SFX_Slots_New_Spin
	sfx_pointer SFX_Shooting_Star
	
	sfx_pointer Music_TitleScreen
	sfx_pointer Music_Credits
	;sfx_pointer Music_HallOfFame
	sfx_pointer Music_OaksLab
	sfx_pointer Music_JigglypuffSong
	sfx_pointer Music_BikeRiding
	sfx_pointer Music_Surfing
	sfx_pointer Music_GameCorner
	sfx_pointer Music_IntroBattle
	sfx_pointer Music_Dungeon1
	sfx_pointer Music_Dungeon2
	sfx_pointer Music_Dungeon3
	sfx_pointer Music_CinnabarMansion
	sfx_pointer Music_PokemonTower
	sfx_pointer Music_SilphCo
	sfx_pointer Music_MeetEvilTrainer
	sfx_pointer Music_MeetFemaleTrainer
	sfx_pointer Music_MeetMaleTrainer
	