SFX_Pointers::
	db 255,255,255
	sfx_pointer SFX_Snare1
	sfx_pointer SFX_Snare2
	sfx_pointer SFX_Snare3
	sfx_pointer SFX_Snare4
	sfx_pointer SFX_Snare5
	sfx_pointer SFX_Triangle1
	sfx_pointer SFX_Triangle2
	sfx_pointer SFX_Snare6
	sfx_pointer SFX_Snare7
	sfx_pointer SFX_Snare8
	sfx_pointer SFX_Snare9
	sfx_pointer SFX_Cymbal1
	sfx_pointer SFX_Cymbal2
	sfx_pointer SFX_Cymbal3
	sfx_pointer SFX_Muted_Snare1
	sfx_pointer SFX_Triangle3
	sfx_pointer SFX_Muted_Snare2
	sfx_pointer SFX_Muted_Snare3
	sfx_pointer SFX_Muted_Snare4
	
	sfx_pointer SFX_Cry00
	sfx_pointer SFX_Cry01
	sfx_pointer SFX_Cry02
	sfx_pointer SFX_Cry03
	sfx_pointer SFX_Cry04
	sfx_pointer SFX_Cry05
	sfx_pointer SFX_Cry06
	sfx_pointer SFX_Cry07
	sfx_pointer SFX_Cry08
	sfx_pointer SFX_Cry09
	sfx_pointer SFX_Cry0A
	sfx_pointer SFX_Cry0B
	sfx_pointer SFX_Cry0C
	sfx_pointer SFX_Cry0D
	sfx_pointer SFX_Cry0E
	sfx_pointer SFX_Cry0F
	sfx_pointer SFX_Cry10
	sfx_pointer SFX_Cry11
	sfx_pointer SFX_Cry12
	sfx_pointer SFX_Cry13
	sfx_pointer SFX_Cry14
	sfx_pointer SFX_Cry15
	sfx_pointer SFX_Cry16
	sfx_pointer SFX_Cry17
	sfx_pointer SFX_Cry18
	sfx_pointer SFX_Cry19
	sfx_pointer SFX_Cry1A
	sfx_pointer SFX_Cry1B
	sfx_pointer SFX_Cry1C
	sfx_pointer SFX_Cry1D
	sfx_pointer SFX_Cry1E
	sfx_pointer SFX_Cry1F
	sfx_pointer SFX_Cry20
	sfx_pointer SFX_Cry21
	sfx_pointer SFX_Cry22
	sfx_pointer SFX_Cry23
	sfx_pointer SFX_Cry24
	sfx_pointer SFX_Cry25
	sfx_pointer SFX_Cry26
	sfx_pointer SFX_Cry27
	sfx_pointer SFX_Cry28
	sfx_pointer SFX_Cry29
	sfx_pointer SFX_Cry2A
	sfx_pointer SFX_Cry2B
	sfx_pointer SFX_Cry2C
	sfx_pointer SFX_Cry2D
	sfx_pointer SFX_Cry2E
	sfx_pointer SFX_Cry2F
	sfx_pointer SFX_Cry30
	
	sfx_pointer SFX_Get_Item1
	sfx_pointer SFX_Get_Item2
	sfx_pointer SFX_Tink
	sfx_pointer SFX_Heal_HP
	sfx_pointer SFX_Heal_Ailment
	sfx_pointer SFX_Start_Menu
	sfx_pointer SFX_Press_AB
	sfx_pointer SFX_Pokedex_Rating
	sfx_pointer SFX_Get_Key_Item
	sfx_pointer SFX_Poisoned
	sfx_pointer SFX_Trade_Machine
	sfx_pointer SFX_Turn_On_PC
	sfx_pointer SFX_Turn_Off_PC
	sfx_pointer SFX_Enter_PC
	sfx_pointer SFX_Shrink
	sfx_pointer SFX_Switch
	sfx_pointer SFX_Healing_Machine
	sfx_pointer SFX_Teleport_Exit1
	sfx_pointer SFX_Teleport_Enter1
	sfx_pointer SFX_Teleport_Exit2
	sfx_pointer SFX_Ledge
	sfx_pointer SFX_Teleport_Enter2
	sfx_pointer SFX_Fly
	sfx_pointer SFX_Denied
	sfx_pointer SFX_Arrow_Tiles
	sfx_pointer SFX_Push_Boulder
	sfx_pointer SFX_SS_Anne_Horn
	sfx_pointer SFX_Withdraw_Deposit
	sfx_pointer SFX_Cut
	sfx_pointer SFX_Go_Inside
	sfx_pointer SFX_Swap
	sfx_pointer SFX_Unused3
	sfx_pointer SFX_Purchase
	sfx_pointer SFX_Collision
	sfx_pointer SFX_Go_Outside
	sfx_pointer SFX_Save
	sfx_pointer SFX_Pokeflute
	sfx_pointer SFX_Safari_Zone_PA
	sfx_pointer SFX_Level_Up
	sfx_pointer SFX_Ball_Toss
	sfx_pointer SFX_Ball_Poof
	sfx_pointer SFX_Faint_Thud
	sfx_pointer SFX_Run
	sfx_pointer SFX_Dex_Page_Added
	sfx_pointer SFX_Caught_Mon
	sfx_pointer SFX_Peck
	sfx_pointer SFX_Faint_Fall
	sfx_pointer SFX_Battle_09
	sfx_pointer SFX_Pound
	sfx_pointer SFX_Battle_0B
	sfx_pointer SFX_Battle_0C
	sfx_pointer SFX_Battle_0D
	sfx_pointer SFX_Battle_0E
	sfx_pointer SFX_Battle_0F
	sfx_pointer SFX_Damage
	sfx_pointer SFX_Not_Very_Effective
	sfx_pointer SFX_Battle_12
	sfx_pointer SFX_Battle_13
	sfx_pointer SFX_Battle_14
	sfx_pointer SFX_Vine_Whip
	sfx_pointer SFX_Battle_16
	sfx_pointer SFX_Battle_17
	sfx_pointer SFX_Battle_18
	sfx_pointer SFX_Battle_19
	sfx_pointer SFX_Super_Effective
	sfx_pointer SFX_Battle_1B
	sfx_pointer SFX_Battle_1C
	sfx_pointer SFX_Doubleslap
	sfx_pointer SFX_Battle_1E
	sfx_pointer SFX_Horn_Drill
	sfx_pointer SFX_Battle_20
	sfx_pointer SFX_Battle_21
	sfx_pointer SFX_Battle_22
	sfx_pointer SFX_Battle_23
	sfx_pointer SFX_Battle_24
	sfx_pointer SFX_Battle_25
	sfx_pointer SFX_Battle_26
	sfx_pointer SFX_Battle_27
	sfx_pointer SFX_Battle_28
	sfx_pointer SFX_Battle_29
	sfx_pointer SFX_Battle_2A
	sfx_pointer SFX_Battle_2B
	sfx_pointer SFX_Battle_2C
	sfx_pointer SFX_Psybeam
	sfx_pointer SFX_Battle_2E
	sfx_pointer SFX_Battle_2F
	sfx_pointer SFX_Psychic_M
	sfx_pointer SFX_Battle_31
	sfx_pointer SFX_Battle_32
	sfx_pointer SFX_Battle_33
	sfx_pointer SFX_Battle_34
	sfx_pointer SFX_Battle_35
	sfx_pointer SFX_Battle_36
	sfx_pointer SFX_Silph_Scope
	sfx_pointer SFX_Intro_Lunge
	sfx_pointer SFX_Intro_Hip
	sfx_pointer SFX_Intro_Hop
	sfx_pointer SFX_Intro_Raise
	sfx_pointer SFX_Intro_Crash
	sfx_pointer SFX_Intro_Whoosh
	sfx_pointer SFX_Slots_Stop_Wheel
	sfx_pointer SFX_Slots_Reward
	sfx_pointer SFX_Slots_New_Spin
	sfx_pointer SFX_Shooting_Star
	sfx_pointer SFX_Unused
	sfx_pointer SFX_Unused2
	
	sfx_pointer Music_TitleScreen
	sfx_pointer Music_Credits
	sfx_pointer Music_HallOfFame
	sfx_pointer Music_OaksLab
	sfx_pointer Music_JigglypuffSong
	sfx_pointer Music_BikeRiding
	sfx_pointer Music_Surfing
	sfx_pointer Music_GameCorner
	sfx_pointer Music_IntroBattle
	sfx_pointer Music_Dungeon1
	sfx_pointer Music_Dungeon2
	sfx_pointer Music_Dungeon3
	sfx_pointer Music_CinnabarMansion
	sfx_pointer Music_PokemonTower
	sfx_pointer Music_SilphCo
	sfx_pointer Music_MeetEvilTrainer
	sfx_pointer Music_MeetFemaleTrainer
	sfx_pointer Music_MeetMaleTrainer
	sfx_pointer Music_PalletTown
	sfx_pointer Music_Pokecenter
	sfx_pointer Music_Gym
	sfx_pointer Music_Cities1
	sfx_pointer Music_Cities2
	sfx_pointer Music_Celadon
	sfx_pointer Music_Cinnabar
	sfx_pointer Music_Vermilion
	sfx_pointer Music_Lavender
	sfx_pointer Music_SSAnne
	sfx_pointer Music_MeetProfOak
	sfx_pointer Music_MeetRival
	sfx_pointer Music_MuseumGuy
	sfx_pointer Music_SafariZone
	sfx_pointer Music_PkmnHealed
	sfx_pointer Music_Routes1
	sfx_pointer Music_Routes2
	sfx_pointer Music_Routes3
	sfx_pointer Music_Routes4
	sfx_pointer Music_IndigoPlateau
	sfx_pointer Music_GymLeaderBattle
	sfx_pointer Music_TrainerBattle
	sfx_pointer Music_WildBattle
	sfx_pointer Music_FinalBattle
	sfx_pointer Music_DefeatedTrainer
	sfx_pointer Music_DefeatedWildMon
	sfx_pointer Music_DefeatedGymLeader
	