SFX_Pointers_1::
	db 255,255,255
	sfx_pointer SFX_Snare1_1
	sfx_pointer SFX_Snare2_1
	sfx_pointer SFX_Snare3_1
	sfx_pointer SFX_Snare4_1
	sfx_pointer SFX_Snare5_1
	sfx_pointer SFX_Triangle1_1
	sfx_pointer SFX_Triangle2_1
	sfx_pointer SFX_Snare6_1
	sfx_pointer SFX_Snare7_1
	sfx_pointer SFX_Snare8_1
	sfx_pointer SFX_Snare9_1
	sfx_pointer SFX_Cymbal1_1
	sfx_pointer SFX_Cymbal2_1
	sfx_pointer SFX_Cymbal3_1
	sfx_pointer SFX_Muted_Snare1_1
	sfx_pointer SFX_Triangle3_1
	sfx_pointer SFX_Muted_Snare2_1
	sfx_pointer SFX_Muted_Snare3_1
	sfx_pointer SFX_Muted_Snare4_1
	sfx_pointer SFX_Cry00_1
	sfx_pointer SFX_Cry01_1
	sfx_pointer SFX_Cry02_1
	sfx_pointer SFX_Cry03_1
	sfx_pointer SFX_Cry04_1
	sfx_pointer SFX_Cry05_1
	sfx_pointer SFX_Cry06_1
	sfx_pointer SFX_Cry07_1
	sfx_pointer SFX_Cry08_1
	sfx_pointer SFX_Cry09_1
	sfx_pointer SFX_Cry0A_1
	sfx_pointer SFX_Cry0B_1
	sfx_pointer SFX_Cry0C_1
	sfx_pointer SFX_Cry0D_1
	sfx_pointer SFX_Cry0E_1
	sfx_pointer SFX_Cry0F_1
	sfx_pointer SFX_Cry10_1
	sfx_pointer SFX_Cry11_1
	sfx_pointer SFX_Cry12_1
	sfx_pointer SFX_Cry13_1
	sfx_pointer SFX_Cry14_1
	sfx_pointer SFX_Cry15_1
	sfx_pointer SFX_Cry16_1
	sfx_pointer SFX_Cry17_1
	sfx_pointer SFX_Cry18_1
	sfx_pointer SFX_Cry19_1
	sfx_pointer SFX_Cry1A_1
	sfx_pointer SFX_Cry1B_1
	sfx_pointer SFX_Cry1C_1
	sfx_pointer SFX_Cry1D_1
	sfx_pointer SFX_Cry1E_1
	sfx_pointer SFX_Cry1F_1
	sfx_pointer SFX_Cry20_1
	sfx_pointer SFX_Cry21_1
	sfx_pointer SFX_Cry22_1
	sfx_pointer SFX_Cry23_1
	sfx_pointer SFX_Cry24_1
	sfx_pointer SFX_Cry25_1
	sfx_pointer SFX_Cry26_1
	sfx_pointer SFX_Cry27_1
	sfx_pointer SFX_Cry28_1
	sfx_pointer SFX_Get_Item1_1
	sfx_pointer SFX_Get_Item2_1
	sfx_pointer SFX_Tink_1
	sfx_pointer SFX_Heal_HP_1
	sfx_pointer SFX_Heal_Ailment_1
	sfx_pointer SFX_Start_Menu_1
	sfx_pointer SFX_Press_AB_1
	sfx_pointer SFX_Pokedex_Rating_1
	sfx_pointer SFX_Get_Key_Item_1
	sfx_pointer SFX_Poisoned_1
	sfx_pointer SFX_Trade_Machine_1
	sfx_pointer SFX_Turn_On_PC_1
	sfx_pointer SFX_Turn_Off_PC_1
	sfx_pointer SFX_Enter_PC_1
	sfx_pointer SFX_Shrink_1
	sfx_pointer SFX_Switch_1
	sfx_pointer SFX_Healing_Machine_1
	sfx_pointer SFX_Teleport_Exit1_1
	sfx_pointer SFX_Teleport_Enter1_1
	sfx_pointer SFX_Teleport_Exit2_1
	sfx_pointer SFX_Ledge_1
	sfx_pointer SFX_Teleport_Enter2_1
	sfx_pointer SFX_Fly_1
	sfx_pointer SFX_Denied_1
	sfx_pointer SFX_Arrow_Tiles_1
	sfx_pointer SFX_Push_Boulder_1
	sfx_pointer SFX_SS_Anne_Horn_1
	sfx_pointer SFX_Withdraw_Deposit_1
	sfx_pointer SFX_Cut_1
	sfx_pointer SFX_Go_Inside_1
	sfx_pointer SFX_Swap_1
	sfx_pointer SFX_59_1
	sfx_pointer SFX_Purchase_1
	sfx_pointer SFX_Collision_1
	sfx_pointer SFX_Go_Outside_1
	sfx_pointer SFX_Save_1
	sfx_pointer SFX_Pokeflute
	sfx_pointer SFX_Safari_Zone_PA
	sfx_pointer SFX_Level_Up
	sfx_pointer SFX_Ball_Toss
	sfx_pointer SFX_Ball_Poof
	sfx_pointer SFX_Faint_Thud
	sfx_pointer SFX_Run
	sfx_pointer SFX_Dex_Page_Added
	sfx_pointer SFX_Caught_Mon
	sfx_pointer SFX_Peck
	sfx_pointer SFX_Faint_Fall
	sfx_pointer SFX_Battle_09
	sfx_pointer SFX_Pound
	sfx_pointer SFX_Battle_0B
	sfx_pointer SFX_Battle_0C
	sfx_pointer SFX_Battle_0D
	sfx_pointer SFX_Battle_0E
	sfx_pointer SFX_Battle_0F
	sfx_pointer SFX_Damage
	sfx_pointer SFX_Not_Very_Effective
	sfx_pointer SFX_Battle_12
	sfx_pointer SFX_Battle_13
	sfx_pointer SFX_Battle_14
	sfx_pointer SFX_Vine_Whip
	sfx_pointer SFX_Battle_16
	sfx_pointer SFX_Battle_17
	sfx_pointer SFX_Battle_18
	sfx_pointer SFX_Battle_19
	sfx_pointer SFX_Super_Effective
	sfx_pointer SFX_Battle_1B
	sfx_pointer SFX_Battle_1C
	sfx_pointer SFX_Doubleslap
	sfx_pointer SFX_Battle_1E
	sfx_pointer SFX_Horn_Drill
	sfx_pointer SFX_Battle_20
	sfx_pointer SFX_Battle_21
	sfx_pointer SFX_Battle_22
	sfx_pointer SFX_Battle_23
	sfx_pointer SFX_Battle_24
	sfx_pointer SFX_Battle_25
	sfx_pointer SFX_Battle_26
	sfx_pointer SFX_Battle_27
	sfx_pointer SFX_Battle_28
	sfx_pointer SFX_Battle_29
	sfx_pointer SFX_Battle_2A
	sfx_pointer SFX_Battle_2B
	sfx_pointer SFX_Battle_2C
	sfx_pointer SFX_Psybeam
	sfx_pointer SFX_Battle_2E
	sfx_pointer SFX_Battle_2F
	sfx_pointer SFX_Psychic_M
	sfx_pointer SFX_Battle_31
	sfx_pointer SFX_Battle_32
	sfx_pointer SFX_Battle_33
	sfx_pointer SFX_Battle_34
	sfx_pointer SFX_Battle_35
	sfx_pointer SFX_Battle_36
	sfx_pointer SFX_Silph_Scope
	sfx_pointer SFX_Intro_Lunge
	sfx_pointer SFX_Intro_Hip
	sfx_pointer SFX_Intro_Hop
	sfx_pointer SFX_Intro_Raise
	sfx_pointer SFX_Intro_Crash
	sfx_pointer SFX_Intro_Whoosh
	sfx_pointer SFX_Slots_Stop_Wheel
	sfx_pointer SFX_Slots_Reward
	sfx_pointer SFX_Slots_New_Spin
	sfx_pointer SFX_Shooting_Star
	
	sfx_pointer Music_TitleScreen
	sfx_pointer Music_Credits
	sfx_pointer Music_HallOfFame
	sfx_pointer Music_OaksLab
	sfx_pointer Music_JigglypuffSong
	sfx_pointer Music_BikeRiding
	sfx_pointer Music_Surfing
	sfx_pointer Music_GameCorner
	sfx_pointer Music_IntroBattle
	sfx_pointer Music_Dungeon1
	sfx_pointer Music_Dungeon2
	sfx_pointer Music_Dungeon3
	sfx_pointer Music_CinnabarMansion
	sfx_pointer Music_PokemonTower
	sfx_pointer Music_SilphCo
	sfx_pointer Music_MeetEvilTrainer
	sfx_pointer Music_MeetFemaleTrainer
	sfx_pointer Music_MeetMaleTrainer
	sfx_pointer Music_PalletTown
	sfx_pointer Music_Pokecenter
	sfx_pointer Music_Gym
	sfx_pointer Music_Cities1
	sfx_pointer Music_Cities2
	sfx_pointer Music_Celadon
	sfx_pointer Music_Cinnabar
	sfx_pointer Music_Vermilion
	sfx_pointer Music_Lavender
	sfx_pointer Music_SSAnne
	sfx_pointer Music_MeetProfOak
	sfx_pointer Music_MeetRival
	sfx_pointer Music_MuseumGuy
	sfx_pointer Music_SafariZone
	sfx_pointer Music_PkmnHealed
	sfx_pointer Music_Routes1
	sfx_pointer Music_Routes2
	sfx_pointer Music_Routes3
	sfx_pointer Music_Routes4
	sfx_pointer Music_IndigoPlateau
	sfx_pointer Music_GymLeaderBattle
	sfx_pointer Music_TrainerBattle
	sfx_pointer Music_WildBattle
	sfx_pointer Music_FinalBattle
	sfx_pointer Music_DefeatedTrainer
	sfx_pointer Music_DefeatedWildMon
	sfx_pointer Music_DefeatedGymLeader
	