ItemNames: ; 472b (1:472b)
	db "Master Ball@"
	db "Ultra Ball@"
	db "Great Ball@"
	db "Poké Ball@"
	db "Shadow Ball@"
	db "Match Box@"
	db "Raft@"
	db "Night Ball@"
	db "Ardor Ball@"
	db "Day Ball@"
	db "Antidote@"
	db "Burn Heal@"
	db "Ice Heal@"
	db "Awakening@"
	db "Parlyz Heal@"
	db "Full Restore@"
	db "Max Potion@"
	db "Hyper Potion@"
	db "Super Potion@"
	db "Potion@"
	db "Purification@"
	db "Winter Ball@"
	db "Motor@"
	db "White Sand@"
	db "Sea Salt@"
	db "Volcanic Ash@"
	db "Mushroom@"
	db "Horn@"
	db "Escape Rope@"
	db "Repel@"
	db "Rope@"
	db "Summer Ball@"
	db "Holo Ball@"
	db "Watering Pail@"
	db "HP Up@"
	db "Protein@"
	db "Iron@"
	db "Carbos@"
	db "Calcium@"
	db "Rare Candy@"
	db "Heal Ball@"
	db "Helix Fossil@"
	db "Jail Keycard@"
	db "Snakeskin@"
	db "Poké Bandage@"
	db "X Accuracy@"
	db "Artifact@"
	db "Cell Key@"
	db "Nugget@"
	db "Whiskers@"
	db "Lure Ball@"
	db "Full Heal@"
	db "Revive@"
	db "Max Revive@"
	db "Guard Spec.@"
	db "Super Repel@"
	db "Max Repel@"
	db "Dire Hit@"
	db "Log@"
	db "Lipids@"
	db "Goo B-Gone@"
	db "Countercurse@"
	db "Machete@"
	db "Silver@"
	db "X Attack@"
	db "X Defend@"
	db "X Speed@"
	db "X Special@"
	db "Coin Case@"
	db "Scent@"
	db "Sweet Scent@"
	db "Rocket Nav.@"
	db "Poké Flute@"
	db "Torch@"
	db "Flash@"
	db "Liq. Courage@"
	db "Gas Canister@"
	db "Fishing Pole@"
	db "Super Ether@"
	db "Ether@"
	db "Max Ether@"
	db "Elixir@"
	db "Super Elixir@"
	db "Prop. Chamber@"
	db "Nozzle@"
	db "Comb. Chamber@"
	db "Ignition@"
	db "Rocket Key@"
	db "Coolant@"
	db "Platinum@"
	db "Cryo Vial@"
	db "Note Sheet@"
	db "Oxygen Suit@"
	db "Cargo@"
	db "Eggshells@"
	db "Crabshells@"
	db "Dogbone@"
	db "Ectoplasm@"
	db "Berry@"
	db "Gold Berry@"
	db "Repa Berry@"
	db "Mint Berry@"
	db "Pecha Berry@"
	db "Rawst Berry@"
	db "Leppa Berry@"
	db "Persim Berry@"
	db "Cheri Berry@"
	db "Razz Berry@"
	db "Bluk Berry@"
	db "Nanab Berry@"
	db "Fan@"
	db "Implant@"
	db "Sap@"
	db "Moon Stone@"
	db "Upgrade@"
	db "Dragon Scale@"
	db "Quartz@"
	db "Super Cap@"
	db "Grills@"
	db "Black Belt@"
	db "Charcoal@"
	db "Skull@"
	db "Adhesive@"
	db "Horseshoe@"
	db "Chiller@"
	db "Wand@"
	db "Steel Coat@"
	db "Antenna@"
	db "King's Rock@"
	db "Thorns@"
	db "Venom Vial@"
	db "Revigator@"
	db "Megaphone@"
	db "Whetstone@"
	db "Pump@"
	db "Windbreaker@"
	db "Cast@"
	db "Bug Spray@"
	db "Night Light@"
	db "Dubious Disc@"
	db "Dragon Glass@"
	db "Spade@"
	db "Rubber Coat@"
	db "Cayenne@"
	db "Punching Bag@"
	db "Heat Blanket@"
	db "Cross@"
	db "Grease@"
	db "Reins@"
	db "Ice Melt@"
	db "Defend Charm@"
	db "Magnet@"
	db "Tinfoil@"
	db "Cushion@"
	db "Deweed@"
	db "Gas Mask@"
	db "Lead Jacket@"
	db "Earmuffs@"
	db "Clippers@"
	db "Umbrella@"
	db "Clover@"
	db "Camouflage@"
	db "Power Brace@"
	db "Guard Brace@"
	db "Quick Brace@"
	db "Force Brace@"
	db "Vital Brace@"
	db "Energy Brace@"
	db "Exp. Share@"
	db "Happy Stone@"
	db "Macho Brace@"
	db "Goggles@"
	db "Weather Orb@"
	db "Focus Band@"
	
ElevatorFloorNames::
	db "B4F@"
	db "B3F@"
	db "B2F@"
	db "B1F@"
	db "1F@"
	db "2F@"
	db "3F@"
	db "4F@"
	db "5F@"
	db "6F@"
	db "7F@"
	db "8F@"
	db "9F@"
	db "10F@"
	db "11F@"