MoveNames:: ; b0000 (2c:4000)
	db "Pound@"
	db "Karate Chop@"
	db "Starburst@"
	db "Comet Punch@"
	db "Mega Punch@"
	db "Pay Day@"
	db "Fire Punch@"
	db "Ice Punch@"
	db "Thunderpunch@"
	db "Scratch@"
	db "Vicegrip@"
	db "Disembowel@"
	db "Razor Wind@"
	db "Cosmic Ray@"
	db "Stab@"
	db "Gust@"
	db "Wing Attack@"
	db "Whirlwind@"
	db "Fly@"
	db "Bind@"
	db "Slam@"
	db "Vine Whip@"
	db "Stomp@"
	db "Double Kick@"
	db "Mega Kick@"
	db "Jump Kick@"
	db "Virtual Reality@"
	db "Sand-attack@"
	db "Headbutt@"
	db "Horn Attack@"
	db "Fury Attack@"
	db "Horn Drill@"
	db "Tackle@"
	db "Body Slam@"
	db "Eclipse@"
	db "Take Down@"
	db "Thrash@"
	db "Osteoblast@"
	db "Splinter@"
	db "Poison Sting@"
	db "Dreadnought@"
	db "Pin Missile@"
	db "Leer@"
	db "Bite@"
	db "Growl@"
	db "Roar@"
	db "Sing@"
	db "Supersonic@"
	db "Sonicboom@"
	db "Disable@"
	db "Acid@"
	db "Ember@"
	db "Flamethrower@"
	db "Clone@"
	db "Snowball@"
	db "Hydro Cannon@"
	db "Lava@"
	db "Ice Beam@"
	db "Blizzard@"
	db "Psybeam@"
	db "Bubblebeam@"
	db "Aurora Beam@"
	db "Hyper Beam@"
	db "Peck@"
	db "Drill Peck@"
	db "Submission@"
	db "Low Kick@"
	db "Counter@"
	db "Genesis@"
	db "Telekinesis@"
	db "Bloodsuck@"
	db "Cyber Beam@"
	db "Leech Seed@"
	db "Calcify@"
	db "Razor Leaf@"
	db "Solarbeam@"
	db "Poisonpowder@"
	db "Stun Spore@"
	db "Sleep Powder@"
	db "Bug Bite@"
	db "String Shot@"
	db "Dragon Rage@"
	db "Fire Spin@"
	db "Thundershock@"
	db "Thunderbolt@"
	db "Thunder Wave@"
	db "Thunder@"
	db "Rock Throw@"
	db "Earthquake@"
	db "Fissure@"
	db "Dig@"
	db "Toxic@"
	db "Confusion@"
	db "Psychic@"
	db "Hypnosis@"
	db "Meditate@"
	db "Tornado@"
	db "Quick Attack@"
	db "Rage@"
	db "Teleport@"
	db "Night Shade@"
	db "Telepathic@"
	db "Screech@"
	db "Triple Peck@"
	db "Recover@"
	db "Harden@"
	db "Acid Silk@"
	db "Molt@"
	db "Confuse Ray@"
	db "Asteroid Pelt@"
	db "Defense Curl@"
	db "Bioshock@"
	db "Light Screen@"
	db "Supernova@"
	db "Voodoo@"
	db "Focus Energy@"
	db "Bide@"
	db "Magic Dice@"
	db "Echo@"
	db "Selfdestruct@"
	db "Egg Bomb@"
	db "Lick@"
	db "Smog@"
	db "Sludge@"
	db "Bone Club@"
	db "Fire Blast@"
	db "Waterfall@"
	db "Clamp@"
	db "Brutal Galaxy@"
	db "Skull Bash@"
	db "Spike Cannon@"
	db "Constrict@"
	db "Gale Force@"
	db "Waterspout@"
	db "Softboiled@"
	db "Hi jump Kick@"
	db "Glare@"
	db "Dream Eater@"
	db "Toxic Gas@"
	db "Sonar@"
	db "Leech Life@"
	db "Sting@"
	db "Sky Attack@"
	db "Transform@"
	db "Raptor Strike@"
	db "Cyber Attack@"
	db "Spore@"
	db "Charge@"
	db "Psywave@"
	db "Splash@"
	db "Acid Armor@"
	db "Drench@"
	db "Wight Walker@"
	db "Fury Swipes@"
	db "Bonemerang@"
	db "Rest@"
	db "Rock Slide@"
	db "Hyper Fang@"
	db "Sharpen@"
	db "Conversion@"
	db "Hasten@"
	db "Super Fang@"
	db "Slash@"
	db "Substitute@"
	db "Struggle@"
	db "Compress@"
	db "Firewall@"
	db "Computer Virus@"
	db "Dragon Breath@"
	db "Dragon Dance@"
	db "Dracarys@"
	db "Serpent Scorn@"
	db "Dragonspeed@"
	db "Sandstorm@"
	db "Landslide@"
	db "Quicksand@"
	db "Shock@"
	db "Super Conductor@"
	db "Amp Stamp@"
	db "Thunderstorm@"
	db "Chomp@"
	db "Bone Crusher@"
	db "Sabertooth@"
	db "Feral@"
	db "Monkey Fist@"
	db "Haymaker@"
	db "Roundhouse@"
	db "Chokehold@"
	db "Firestorm@"
	db "Inferno@"
	db "Eruption@"
	db "Night Terror@"
	db "Dissipate@"
	db "Haunt@"
	db "Spook@"
	db "Sticky Bomb@"
	db "Goo Toss@"
	db "Slime@"
	db "Rear Kick@"
	db "Gore@"
	db "Bulldoze@"
	db "Refraction@"
	db "Luminance@"
	db "Bellow@"
	db "Hail Storm@"
	db "Avalanche@"
	db "Arctic Freeze@"
	db "Iceball@"
	db "Icicle Spear@"
	db "Glacial Fall@"
	db "Adaptability@"
	db "Avada Kedavra@"
	db "Hocus Pocus@"
	db "Spell Cast@"
	db "Black Magic@"
	db "Incense@"
	db "Fairy Dust@"
	db "Iron Curtain@"
	db "Heat Treat@"
	db "Heavy Metal@"
	db "Annodize@"
	db "Steel Burst@"
	db "Shrapnel@"
	db "Iron Tail@"
	db "Inner Peace@"
	db "Occlumency@"
	db "Flytrap@"
	db "Tail Slap@"
	db "Spearhead@"
	db "Sunlight@"
	db "Pollen Blast@"
	db "Poison Ivy@"
	db "Timber@"
	db "Thorn Mace@"
	db "Injection@"
	db "Venom Shot@"
	db "Atomic Boom@"
	db "Gamma ray Burst@"
	db "Radiate@"
	db "Pulsar@"
	db "Decay@"
	db "Tsunami@"
	db "Half Life@"
	db "Shadow Surge@"
	db "Shadow Figure@"
	db "Amplifier@"
	db "Sonic Wave@"
	db "Landmine@"
	db "Howl@"
	db "Piercing Scream@"
	db "Razor Claw@"
	db "Cross Slash@"
	db "Shred@"
	db "Whirlpool@"