MoveNames:: ; b0000 (2c:4000)
	db "POUND@"
	db "KARATE CHOP@"
	db "STARBURST@"
	db "COMET PUNCH@"
	db "MEGA PUNCH@"
	db "PAY DAY@"
	db "FIRE PUNCH@"
	db "ICE PUNCH@"
	db "THUNDERPUNCH@"
	db "SCRATCH@"
	db "VICEGRIP@"
	db "DISEMBOWEL@"
	db "RAZOR WIND@"
	db "COSMIC RAY@"
	db "STAB@"
	db "GUST@"
	db "WING ATTACK@"
	db "WHIRLWIND@"
	db "FLY@"
	db "BIND@"
	db "SLAM@"
	db "VINE WHIP@"
	db "STOMP@"
	db "DOUBLE KICK@"
	db "MEGA KICK@"
	db "JUMP KICK@"
	db "VIRTUAL REALITY@"
	db "SAND-ATTACK@"
	db "HEADBUTT@"
	db "HORN ATTACK@"
	db "FURY ATTACK@"
	db "HORN DRILL@"
	db "TACKLE@"
	db "BODY SLAM@"
	db "ECLIPSE@"
	db "TAKE DOWN@"
	db "THRASH@"
	db "OSTEOBLAST@"
	db "SPLINTER@"
	db "POISON STING@"
	db "DREADNOUGHT@"
	db "PIN MISSILE@"
	db "LEER@"
	db "BITE@"
	db "GROWL@"
	db "ROAR@"
	db "SING@"
	db "SUPERSONIC@"
	db "SONICBOOM@"
	db "DISABLE@"
	db "ACID@"
	db "EMBER@"
	db "FLAMETHROWER@"
	db "CLONE@"
	db "SNOWBALL@"
	db "HYDRO CANNON@"
	db "LAVA@"
	db "ICE BEAM@"
	db "BLIZZARD@"
	db "PSYBEAM@"
	db "BUBBLEBEAM@"
	db "AURORA BEAM@"
	db "HYPER BEAM@"
	db "PECK@"
	db "DRILL PECK@"
	db "SUBMISSION@"
	db "LOW KICK@"
	db "COUNTER@"
	db "GENESIS@"
	db "TELEKINESIS@"
	db "BLOODSUCK@"
	db "CYBER BEAM@"
	db "LEECH SEED@"
	db "CALCIFY@"
	db "RAZOR LEAF@"
	db "SOLARBEAM@"
	db "POISONPOWDER@"
	db "STUN SPORE@"
	db "SLEEP POWDER@"
	db "BUG BITE@"
	db "STRING SHOT@"
	db "DRAGON RAGE@"
	db "FIRE SPIN@"
	db "THUNDERSHOCK@"
	db "THUNDERBOLT@"
	db "THUNDER WAVE@"
	db "THUNDER@"
	db "ROCK THROW@"
	db "EARTHQUAKE@"
	db "FISSURE@"
	db "DIG@"
	db "TOXIC@"
	db "CONFUSION@"
	db "PSYCHIC@"
	db "HYPNOSIS@"
	db "MEDITATE@"
	db "TORNADO@"
	db "QUICK ATTACK@"
	db "RAGE@"
	db "TELEPORT@"
	db "NIGHT SHADE@"
	db "TELEPATHIC@"
	db "SCREECH@"
	db "TRIPLE PECK@"
	db "RECOVER@"
	db "HARDEN@"
	db "ACID SILK@"
	db "MOLT@"
	db "CONFUSE RAY@"
	db "ASTEROID PELT@"
	db "DEFENSE CURL@"
	db "BIOSHOCK@"
	db "LIGHT SCREEN@"
	db "SUPERNOVA@"
	db "VOODOO@"
	db "FOCUS ENERGY@"
	db "BIDE@"
	db "MAGIC DICE@"
	db "ECHO@"
	db "SELFDESTRUCT@"
	db "EGG BOMB@"
	db "LICK@"
	db "SMOG@"
	db "SLUDGE@"
	db "BONE CLUB@"
	db "FIRE BLAST@"
	db "WATERFALL@"
	db "CLAMP@"
	db "BRUTAL GALAXY@"
	db "SKULL BASH@"
	db "SPIKE CANNON@"
	db "CONSTRICT@"
	db "GALE FORCE@"
	db "WATERSPOUT@"
	db "SOFTBOILED@"
	db "HI JUMP KICK@"
	db "GLARE@"
	db "DREAM EATER@"
	db "TOXIC GAS@"
	db "SONAR@"
	db "LEECH LIFE@"
	db "STING@"
	db "SKY ATTACK@"
	db "TRANSFORM@"
	db "RAPTOR STRIKE@"
	db "CYBER ATTACK@"
	db "SPORE@"
	db "CHARGE@"
	db "PSYWAVE@"
	db "SPLASH@"
	db "ACID ARMOR@"
	db "DRENCH@"
	db "WIGHT WALKER@"
	db "FURY SWIPES@"
	db "BONEMERANG@"
	db "REST@"
	db "ROCK SLIDE@"
	db "HYPER FANG@"
	db "SHARPEN@"
	db "CONVERSION@"
	db "HASTEN@"
	db "SUPER FANG@"
	db "SLASH@"
	db "SUBSTITUTE@"
	db "STRUGGLE@"
	db "COMPRESS@"
	db "FIREWALL@"
	db "COMPUTER VIRUS@"
	db "DRAGON BREATH@"
	db "DRAGON DANCE@"
	db "DRACARYS@"
	db "SERPENT SCORN@"
	db "DRAGONSPEED@"
	db "SANDSTORM@"
	db "LANDSLIDE@"
	db "QUICKSAND@"
	db "SHOCK@"
	db "SUPER CONDUCTOR@"
	db "AMP STAMP@"
	db "THUNDERSTORM@"
	db "CHOMP@"
	db "BONE CRUSHER@"
	db "SABERTOOTH@"
	db "FERAL@"
	db "MONKEY FIST@"
	db "HAYMAKER@"
	db "ROUNDHOUSE@"
	db "CHOKEHOLD@"
	db "FIRESTORM@"
	db "INFERNO@"
	db "ERUPTION@"
	db "NIGHT TERROR@"
	db "DISSIPATE@"
	db "HAUNT@"
	db "SPOOK@"
	db "STICKY BOMB@"
	db "GOO TOSS@"
	db "SLIME@"
	db "REAR KICK@"
	db "GORE@"
	db "BULLDOZE@"
	db "REFRACTION@"
	db "LUMINANCE@"
	db "BELLOW@"
	db "HAIL STORM@"
	db "AVALANCHE@"
	db "ARCTIC FREEZE@"
	db "ICEBALL@"
	db "ICICLE SPEAR@"
	db "GLACIAL FALL@"
	db "ADAPTABILITY@"
	db "AVADA KEDAVRA@"
	db "HOCUS POCUS@"
	db "SPELL CAST@"
	db "BLACK MAGIC@"
	db "INCENSE@"
	db "FAIRY DUST@"
	db "IRON CURTAIN@"
	db "HEAT TREAT@"
	db "HEAVY METAL@"
	db "ANNODIZE@"
	db "STEEL BURST@"
	db "SHRAPNEL@"
	db "IRON TAIL@"
	db "INNER PEACE@"
	db "OCCLUMENCY@"
	db "FLYTRAP@"
	db "TAIL SLAP@"
	db "SPEARHEAD@"
	db "SUNLIGHT@"
	db "POLLEN BLAST@"
	db "POISON IVY@"
	db "TIMBER@"
	db "THORN MACE@"
	db "INJECTION@"
	db "VENOM SHOT@"
	db "ATOMIC BOOM@"
	db "GAMMA RAY BURST@"
	db "RADIATE@"
	db "PULSAR@"
	db "DECAY@"
	db "TSUNAMI@"
	db "HALF LIFE@"
	db "SHADOW SURGE@"
	db "SHADOW FIGURE@"
	db "AMPLIFIER@"
	db "SONIC WAVE@"
	db "LANDMINE@"
	db "HOWL@"
	db "PIERCING SCREAM@"
	db "RAZOR CLAW@"
	db "CROSS SLASH@"
	db "SHRED@"
	db "WHIRLPOOL@"