TrainerNames: ; 399ff (e:59ff)
	db "Youngster@"
	db "Bug Catcher@"
	db "Lass@"
	db "Businesslady@"
	db "Witch@"
	db "Sword Master@"
	db "Pokémaniac@"
	db "Mechanic@"
	db "Hiker@"
	db "Kindler@"
	db "Burglar@"
	db "Engineer@"
	db "Juggler@"
	db "Fisherman@"
	db "Swimmer@"
	db "Gardener@"
	db "Gambler@"
	db "Beauty@"
	db "Police Chief@"
	db "Rocker@"
	db "Juggler@"
	db "Tamer@"
	db "Bird Keeper@"
	db "Blackbelt@"
	db "RIVAL1@"
	db "Prof. Oak@"
	db "Ash@"
	db "Scientist@"
	db "Giovanni@"
	db "Police@"
	db "Cooltrainer@"
	db "Cooltrainer@"
	db "Elder Kraken@"
	db "Mayor Ryder@"
	db "Mayor Carol@"
	db "CEO Maxwell@"
	db "Mayor Holly@"
	db "Mayor Cliff@"
	db "Mayor Dante@"
	db "Mayor Savana@"
	db "Gentleman@"
	db "RIVAL2@"
	db "RIVAL3@"
	db "King Apollo@"
	db "Sorcerer@"
	db "Elder Skylar@"
	db "Mayor Caspar@"
