TrainerNames: ; 399ff (e:59ff)
	db "YOUNGSTER@"
	db "BUG CATCHER@"
	db "LASS@"
	db "BUSINESSLADY@"
	db "WITCH@"
	db "SWORD MASTER@"
	db "POKéMANIAC@"
	db "MECHANIC@"
	db "HIKER@"
	db "KINDLER@"
	db "BURGLAR@"
	db "ENGINEER@"
	db "JUGGLER@"
	db "FISHERMAN@"
	db "SWIMMER@"
	db "GARDENER@"
	db "GAMBLER@"
	db "BEAUTY@"
	db "POLICE CHIEF@"
	db "ROCKER@"
	db "JUGGLER@"
	db "TAMER@"
	db "BIRD KEEPER@"
	db "BLACKBELT@"
	db "RIVAL1@"
	db "PROF. OAK@"
	db "ASH@"
	db "SCIENTIST@"
	db "GIOVANNI@"
	db "POLICE@"
	db "COOLTRAINER♂@"
	db "COOLTRAINER♀@"
	db "ELDER KRAKEN@"
	db "MAYOR RYDER@"
	db "MAYOR CAROL@"
	db "CEO MAXWELL@"
	db "MAYOR HOLLY@"
	db "MAYOR CLIFF@"
	db "MAYOR DANTE@"
	db "MAYOR SAVANA@"
	db "GENTLEMAN@"
	db "RIVAL2@"
	db "RIVAL3@"
	db "KING APOLLO@"
	db "SORCERER@"
	db "ELDER SKYLAR@"
	db "MAYOR CASPAR@"
